version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: voting
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  vote:
    image: diallo2910/voting-app_vote:latest
    networks:
      - frontend
      - backend
    ports:
      - "5000:80"

  result:
    image: diallo2910/voting-app_result:latest
    networks:
      - frontend
      - backend
    ports:
      - "5001:80"

  worker:
    image: diallo2910/voting-app_worker:latest
    networks:
      - backend

volumes:
  db-data:

networks:
  frontend:
  backend:
